debug: false
management.endpoints.web.exposure.include: "*"

logging:
  com.wonjuninfo.projectbord: DEBUG
  org.springframework.web.servlet: DEBUG
  org.hibernate.tye.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:mysql://192.168.0.114:1245/bord
    username: wonjun
    password: wonjun123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
 #   open-in-view: false
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.hibernate.default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
# thymeleaf.cache: false
#  data.rest:
#    base-path: /api
#    detection-strategy: annotated

---

spring:
  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:bord;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: NONE